title: muchi65
description: 無知な私の備忘録：プログラミングなど技術情報を発信しています。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://muchi65.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: muchi65_
github_username:  muchi65
keywords: web3, NFT, PGC
author: muchi65

# Build settings
markdown: kramdown
sass:
  style: compressed 
# paginate: 8
# paginate_path: "/pages/:num"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

  # - jekyll-paginate

jekyll_compose:
  auto_open: true
  EDITOR: code

buildtime: "1700751600"

PJAX: true
MathJax: true

background: /theme/bg.jpg
theme_color: 546E7A

hydrogen-blog:
  date_format: "%b %-d, %Y"